name: laravel-demo-build
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist    

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npx vite build --mode demo

      - name: Clean up
        run: |
          rm -rf node_modules
          rm -rf storage/app/public/activities
          rm -rf storage/app/public/certifications
          rm -rf storage/app/public/logos
          mkdir -p storage/app/private/orders/
      - name: Archive application
        run: tar -czf app.tgz ./*

      - name: SSH SCP and deployment for demo
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.DEMO_SSH_HOST }}
          user: ${{ secrets.DEMO_SSH_USER }}
          pass: ${{ secrets.DEMO_SSH_PASSWORD }}
          port: ${{ secrets.DEMO_SSH_PORT }}
          connect_timeout: 10s
          scp: |
            './app.tgz' => ${{ secrets.DEMO_SSH_DIR }}
          last_ssh: |
            cd ${{ secrets.DEMO_SSH_DIR }}
            tar -xzf app.tgz
            composer install --optimize-autoloader --no-dev
            npm install --production
            cp env.example .env
            sed -i "s/APP_ENV=.*/APP_ENV=${{ secrets.DEMO_APP_ENV }}/" .env
            sed -i "s/VITE_APP_ENV=.*/VITE_APP_ENV=${{ secrets.DEMO_VITE_APP_ENV }}/" .env
            sed -i "s/DB_CONNECTION=.*/DB_CONNECTION=${{ secrets.DEMO_DB_CONNECTION }}/" .env
            sed -i "s/DB_HOST=.*/DB_HOST=${{ secrets.DEMO_DB_HOST }}/" .env
            sed -i "s/DB_PORT=.*/DB_PORT=${{ secrets.DEMO_DB_PORT }}/" .env
            sed -i "s/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DEMO_DB_DATABASE }}/" .env
            sed -i "s/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DEMO_DB_USERNAME }}/" .env
            sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DEMO_DB_PASSWORD }}/" .env
            php artisan migrate --force
            php artisan db:seed --force
            php artisan storage:link
            mkdir -p storage/framework/views
            chown -R www-data:www-data storage
            chmod -R 775 storage
            php artisan key:generate 